services:
  regression:
    image: ui_tests
    container_name: ui_tests
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - ./:/swgoh_test_project
    command: python3
    working_dir: /swgoh_test_project/
