from selenium.webdriver.common.by import By


filter_button_loc = (By.XPATH, "//button[@class='btn btn-default']")
filter_list_loc = (By.XPATH, "//div[@class='modal-body p-a-0 categories']/div[@class='modal-body-scroller']"
                             "/div[@class='media-list media-list-users list-group']")
ability_button_filter_loc = (By.XPATH, "//a[text()='Ability Classes']")
alignments_button_filter_loc = (By.XPATH, "//a[text()='Alignments']")
filtered_characters_loc = (By.XPATH, "//small[@class='pull-right']")
#
#
#
#
filter_loc_501 = (By.XPATH, "//strong[text()='501st']")
filter_loc_Attacker = (By.XPATH, "//strong[text()='Attacker']")
filter_loc_Bad_Batch = (By.XPATH, "//strong[text()='Bad Batch']")
filter_loc_Bounty_Hunter = (By.XPATH, "//strong[text()='Bounty Hunter']")
filter_loc_Clone_Trooper = (By.XPATH, "//strong[text()='Clone Trooper']")
filter_loc_Droid = (By.XPATH, "//strong[text()='Droid']")
filter_loc_Empire = (By.XPATH, "//strong[text()='Empire']")
filter_loc_Ewok = (By.XPATH, "//strong[text()='Ewok']")
filter_loc_First_Order = (By.XPATH, "//strong[text()='First Order']")
filter_loc_Fleet_Commander = (By.XPATH, "//strong[text()='Fleet Commander']")
filter_loc_Galactic_Legend = (By.XPATH, "//strong[text()='Galactic Legend']")
filter_loc_Galactic_Republic = (By.XPATH, "//strong[text()='Galactic Republic']")
filter_loc_Geonosian = (By.XPATH, "//strong[text()='Geonosian']")
filter_loc_Healer = (By.XPATH, "//strong[text()='Healer']")
filter_loc_Hutt_Cartel = (By.XPATH, "//strong[text()='Hutt Cartel']")
filter_loc_Imperial_Remnant = (By.XPATH, "//strong[text()='Imperial Remnant']")
filter_loc_Imperial_Trooper = (By.XPATH, "//strong[text()='Imperial Trooper']")
filter_loc_Inquisitorius = (By.XPATH, "//strong[text()='Inquisitorius']")
filter_loc_Jawa = (By.XPATH, "//strong[text()='Jawa']")
filter_loc_Jedi = (By.XPATH, "//strong[text()='Jedi']")
filter_loc_Leader = (By.XPATH, "//strong[text()='Leader']")
filter_loc_Mandalorian = (By.XPATH, "//strong[text()='Mandalorian']")
filter_loc_Nightsister = (By.XPATH, "//strong[text()='Nightsister']")
filter_loc_Old_Republic = (By.XPATH, "//strong[text()='Old Republic']")
filter_loc_Phoenix = (By.XPATH, "//strong[text()='Phoenix']")
filter_loc_Rebel = (By.XPATH, "//strong[text()='Rebel']")
filter_loc_Rebel_Fighter = (By.XPATH, "//strong[text()='Rebel Fighter']")
filter_loc_Resistance = (By.XPATH, "//strong[text()='Resistance']")
filter_loc_Rogue_One = (By.XPATH, "//strong[text()='Rogue One']")
filter_loc_Scoundrel = (By.XPATH, "//strong[text()='Scoundrel']")
filter_loc_Separatist = (By.XPATH, "//strong[text()='Separatist']")
filter_loc_Sith = (By.XPATH, "//strong[text()='Sith']")
filter_loc_Sith_Empire = (By.XPATH, "//strong[text()='Sith Empire']")
filter_loc_Smuggler = (By.XPATH, "//strong[text()='Smuggler']")
filter_loc_Support = (By.XPATH, "//strong[text()='Support']")
filter_loc_Tank = (By.XPATH, "//strong[text()='Tank']")
filter_loc_Tusken = (By.XPATH, "//strong[text()='Tusken']")
filter_loc_Unaligned_Force_User = (By.XPATH, "//strong[text()='Unaligned Force User']")
filter_loc_Wookiee = (By.XPATH, "//strong[text()='Wookiee']")
filter_loc_Light_Side = (By.XPATH, "//strong[text()='Light Side']")
filter_loc_Dark_Side = (By.XPATH, "//strong[text()='Dark Side']")
filter_loc_Neutral = (By.XPATH, "//strong[text()='Neutral']")
#
#
#
#
filter_loc_Ability_Block = (By.XPATH, "//strong[text()='Ability Block']")
filter_loc_Advantage = (By.XPATH, "//strong[text()='Advantage']")
filter_loc_Anti_Droid = (By.XPATH, "//strong[text()='Anti-Droid']")
filter_loc_AoE = (By.XPATH, "//strong[text()='AoE']")
filter_loc_Armor_Shred = (By.XPATH, "//strong[text()='Armor Shred']")
filter_loc_Assist = (By.XPATH, "//strong[text()='Assist']")
filter_loc_Blind = (By.XPATH, "//strong[text()='Blind']")
filter_loc_Bonus_Attack = (By.XPATH, "//strong[text()='Bonus Attack']")
filter_loc_Buff_Immunity = (By.XPATH, "//strong[text()='Buff Immunity']")
filter_loc_Burning = (By.XPATH, "//strong[text()='Burning']")
filter_loc_Counter = (By.XPATH, "//strong[text()='Counter']")
filter_loc_Critical_Chance_Down = (By.XPATH, "//strong[text()='Critical Chance Down']")
filter_loc_Critical_Chance_Up = (By.XPATH, "//strong[text()='Critical Chance Up']")
filter_loc_Critical_Damage_Up = (By.XPATH, "//strong[text()='Critical Damage Up']")
filter_loc_Critical_Hit_Immunity = (By.XPATH, "//strong[text()='Critical Hit Immunity']")
filter_loc_Damage_Immunity = (By.XPATH, "//strong[text()='Damage Immunity']")
filter_loc_Daze = (By.XPATH, "//strong[text()='Daze']")
filter_loc_Deathmark = (By.XPATH, "//strong[text()='Deathmark']")
filter_loc_Defence_Down = (By.XPATH, "//strong[text()='Defence Down']")
filter_loc_Defence_Penetration_Up = (By.XPATH, "//strong[text()='Defence Penetration Up']")
filter_loc_Defence_Up = (By.XPATH, "//strong[text()='Defence Up']")
filter_loc_Dispel = (By.XPATH, "//strong[text()='Dispel']")
filter_loc_Dispel_All_Allies = (By.XPATH, "//strong[text()='Dispel - All Allies']")
filter_loc_Dispel_All_Enemies = (By.XPATH, "//strong[text()='Dispel - All Enemies']")
filter_loc_DoT = (By.XPATH, "//strong[text()='DoT']")
filter_loc_Evasion_Down = (By.XPATH, "//strong[text()='Evasion Down']")
filter_loc_Evasion_Up = (By.XPATH, "//strong[text()='Evasion Up']")
filter_loc_Expose = (By.XPATH, "//strong[text()='Expose']")
filter_loc_Foresight = (By.XPATH, "//strong[text()='Foresight']")
filter_loc_Frenzy = (By.XPATH, "//strong[text()='Frenzy']")
filter_loc_Gain_Turn_Meter = (By.XPATH, "//strong[text()='Gain Turn Meter']")
filter_loc_Heal = (By.XPATH, "//strong[text()='Heal']")
filter_loc_Healing_Immunity = (By.XPATH, "//strong[text()='Healing Immunity']")
filter_loc_Health_Steal_Up = (By.XPATH, "//strong[text()='Health Steal Up']")
filter_loc_Health_Up = (By.XPATH, "//strong[text()='Health Up']")
filter_loc_Inspired = (By.XPATH, "//strong[text()='Inspired']")
filter_loc_Instant_Defeat_Immunity = (By.XPATH, "//strong[text()='Instant Defeat Immunity']")
filter_loc_Leader_Critical_Up = (By.XPATH, "//strong[text()='Leader: +Critical']")
filter_loc_Leader_Defense_Up = (By.XPATH, "//strong[text()='Leader: +Defense']")
filter_loc_Leader_Evasion_Up = (By.XPATH, "//strong[text()='Leader: +Evasion']")
filter_loc_Leader_Max_Health_Up = (By.XPATH, "//strong[text()='Leader: +Max Health']")
filter_loc_Leader_Speed_Up = (By.XPATH, "//strong[text()='Leader: +Speed']")
filter_loc_Leader_Tenacity_Up = (By.XPATH, "//strong[text()='Leader: +Tenacity']")
filter_loc_Leader_Assist = (By.XPATH, "//strong[text()='Leader: Assist']")
filter_loc_Leader_Foresight = (By.XPATH, "//strong[text()='Leader: Foresight']")
filter_loc_Leader_Healing = (By.XPATH, "//strong[text()='Leader: Healing']")
filter_loc_Leader_Health_Up = (By.XPATH, "//strong[text()='Leader: Health Up']")
filter_loc_Leader_Protection_Up = (By.XPATH, "//strong[text()='Leader: Protection Up']")
filter_loc_Offense_Down = (By.XPATH, "//strong[text()='Offense Down']")
filter_loc_Offense_Up = (By.XPATH, "//strong[text()='Offense Up']")
filter_loc_Potency_Down = (By.XPATH, "//strong[text()='Potency Down']")
filter_loc_Potency_Up = (By.XPATH, "//strong[text()='Potency Up']")
filter_loc_Protection_Up = (By.XPATH, "//strong[text()='Protection Up']")
filter_loc_Purge = (By.XPATH, "//strong[text()='Purge']")
filter_loc_Reduce_Cooldowns = (By.XPATH, "//strong[text()='Reduce Cooldowns']")
filter_loc_Remove_Turn_Meter = (By.XPATH, "//strong[text()='Remove Turn Meter']")
filter_loc_Reset_Cooldown = (By.XPATH, "//strong[text()='Reset Cooldown']")
filter_loc_Revive = (By.XPATH, "//strong[text()='Revive']")
filter_loc_Shock = (By.XPATH, "//strong[text()='Shock']")
filter_loc_Speed_Down = (By.XPATH, "//strong[text()='Speed Down']")
filter_loc_Speed_Up = (By.XPATH, "//strong[text()='Speed Up']")
filter_loc_Stagger = (By.XPATH, "//strong[text()='Stagger']")
filter_loc_Stealth = (By.XPATH, "//strong[text()='Stealth']")
filter_loc_Stun = (By.XPATH, "//strong[text()='Stun']")
filter_loc_Target_Lock = (By.XPATH, "//strong[text()='Target Lock']")
filter_loc_Taunt = (By.XPATH, "//strong[text()='Taunt']")
filter_loc_Tenacity_Down = (By.XPATH, "//strong[text()='Tenacity Down']")
filter_loc_Tenacity_Up = (By.XPATH, "//strong[text()='Tenacity Up']")
filter_loc_Thermal_Detonator = (By.XPATH, "//strong[text()='Thermal Detonator']")
filter_loc_Torture = (By.XPATH, "//strong[text()='Torture']")
filter_loc_Vulnerable = (By.XPATH, "//strong[text()='Vulnerable']")
#
#
#
#
all_characters_loc = (By.XPATH, "//li[@class = 'media list-group-item p-0 character']")
