accept_all_cookies_btn_loc = ("id", "cmpbntyestxt")
cookies_frame_loc = ("id", "cmpbox")
#
#
#
filter_button_loc = ("xpath", "//button[@class='button h-100  ']")
filter_list_loc = ("xpath", "//div[@class='modal-content']/div[@class='modal-body']"
                            "/div[@class = 'tab-content']"
                            "/div[@class = 'tab-pane active show']"
                            "/a[@class = 'link-no-style d-block py-2']")
ability_button_filter_loc = ("id", "unit-active-filter-tab-ac")
alignments_button_filter_loc = ("xpath", "//a[text()='Alignments']")
names_of_filtered_chars_loc = ("xpath", "//div[@class = 'unit-card__name']")
filtered_characters_loc = ("xpath", "//div[@class = 'unit-card-grid__cell js-unit-search__result']")
#
#
#
filter_loc_501 = ("xpath", "//a[normalize-space(text()) ='501st']")
filter_loc_Attacker = ("xpath", "//a[normalize-space(text()) ='Attacker']")
filter_loc_Bad_Batch = ("xpath", "//a[normalize-space(text()) ='Bad Batch']")
filter_loc_Bounty_Hunter = ("xpath", "//a[normalize-space(text()) ='Bounty Hunter']")
filter_loc_Clone_Trooper = ("xpath", "//a[normalize-space(text()) ='Clone Trooper']")
filter_loc_Droid = ("xpath", "//a[normalize-space(text()) ='Droid']")
filter_loc_Empire = ("xpath", "//a[normalize-space(text()) ='Empire']")
filter_loc_Ewok = ("xpath", "//a[normalize-space(text()) ='Ewok']")
filter_loc_First_Order = ("xpath", "//a[normalize-space(text()) ='First Order']")
filter_loc_Fleet_Commander = ("xpath", "//a[normalize-space(text()) ='Fleet Commander']")
filter_loc_Galactic_Legend = ("xpath", "//a[normalize-space(text()) ='Galactic Legend']")
filter_loc_Galactic_Republic = ("xpath", "//a[normalize-space(text()) ='Galactic Republic']")
filter_loc_Geonosian = ("xpath", "//a[normalize-space(text()) ='Geonosian']")
filter_loc_Gungan = ("xpath", "//a[normalize-space(text()) ='Gungan']")
filter_loc_Healer = ("xpath", "//a[normalize-space(text()) ='Healer']")
filter_loc_Hutt_Cartel = ("xpath", "//a[normalize-space(text()) ='Hutt Cartel']")
filter_loc_Imperial_Remnant = ("xpath", "//a[normalize-space(text()) ='Imperial Remnant']")
filter_loc_Imperial_Trooper = ("xpath", "//a[normalize-space(text()) ='Imperial Trooper']")
filter_loc_Inquisitorius = ("xpath", "//a[normalize-space(text()) ='Inquisitorius']")
filter_loc_Jawa = ("xpath", "//a[normalize-space(text()) ='Jawa']")
filter_loc_Jedi = ("xpath", "//a[normalize-space(text()) ='Jedi']")
filter_loc_Leader = ("xpath", "//a[normalize-space(text()) ='Leader']")
filter_loc_Mandalorian = ("xpath", "//a[normalize-space(text()) ='Mandalorian']")
filter_loc_Nightsister = ("xpath", "//a[normalize-space(text()) ='Nightsister']")
filter_loc_Old_Republic = ("xpath", "//a[normalize-space(text()) ='Old Republic']")
filter_loc_Phoenix = ("xpath", "//a[normalize-space(text()) ='Phoenix']")
filter_loc_Rebel = ("xpath", "//a[normalize-space(text()) ='Rebel']")
filter_loc_Rebel_Fighter = ("xpath", "//a[normalize-space(text()) ='Rebel Fighter']")
filter_loc_Resistance = ("xpath", "//a[normalize-space(text()) ='Resistance']")
filter_loc_Rogue_One = ("xpath", "//a[normalize-space(text()) ='Rogue One']")
filter_loc_Scoundrel = ("xpath", "//a[normalize-space(text()) ='Scoundrel']")
filter_loc_Separatist = ("xpath", "//a[normalize-space(text()) ='Separatist']")
filter_loc_Sith = ("xpath", "//a[normalize-space(text()) ='Sith']")
filter_loc_Sith_Empire = ("xpath", "//a[normalize-space(text()) ='Sith Empire']")
filter_loc_Smuggler = ("xpath", "//a[normalize-space(text()) ='Smuggler']")
filter_loc_Support = ("xpath", "//a[normalize-space(text()) ='Support']")
filter_loc_Tank = ("xpath", "//a[normalize-space(text()) ='Tank']")
filter_loc_Tusken = ("xpath", "//a[normalize-space(text()) ='Tusken']")
filter_loc_Unaligned_Force_User = ("xpath", "//a[normalize-space(text()) ='Unaligned Force User']")
filter_loc_Wookiee = ("xpath", "//a[normalize-space(text()) ='Wookiee']")
filter_loc_Light_Side = ("xpath", "//a[normalize-space(text()) ='Light Side']")
filter_loc_Dark_Side = ("xpath", "//a[normalize-space(text()) ='Dark Side']")
filter_loc_Neutral = ("xpath", "//a[normalize-space(text()) ='Neutral']")
#
#
#
filter_loc_Ability_Block = ("xpath", "//a[normalize-space(text()) ='Ability Block']")
filter_loc_Accuracy_Down = ("xpath", "//a[normalize-space(text()) ='Accuracy Down']")
filter_loc_Accuracy_Up = ("xpath", "//a[normalize-space(text()) ='Accuracy Up']")
filter_loc_Advantage = ("xpath", "//a[normalize-space(text()) ='Advantage']")
filter_loc_Anti_Droid = ("xpath", "//a[normalize-space(text()) ='Anti-Droid']")
filter_loc_AoE = ("xpath", "//a[normalize-space(text()) ='AoE']")
filter_loc_Armor_Shred = ("xpath", "//a[normalize-space(text()) ='Armor Shred']")
filter_loc_Assist = ("xpath", "//a[normalize-space(text()) ='Assist']")
filter_loc_Blind = ("xpath", "//a[normalize-space(text()) ='Blind']")
filter_loc_Bonus_Attack = ("xpath", "//a[normalize-space(text()) ='Bonus Attack']")
filter_loc_Buff_Immunity = ("xpath", "//a[normalize-space(text()) ='Buff Immunity']")
filter_loc_Burning = ("xpath", "//a[normalize-space(text()) ='Burning']")
filter_loc_Counter = ("xpath", "//a[normalize-space(text()) ='Counter']")
filter_loc_Critical_Chance_Down = ("xpath", "//a[normalize-space(text()) ='Critical Chance Down']")
filter_loc_Critical_Chance_Up = ("xpath", "//a[normalize-space(text()) ='Critical Chance Up']")
filter_loc_Critical_Damage_Down = ("xpath", "//a[normalize-space(text()) ='Critical Damage Down']")
filter_loc_Critical_Damage_Up = ("xpath", "//a[normalize-space(text()) ='Critical Damage Up']")
filter_loc_Critical_Hit_Immunity = ("xpath", "//a[normalize-space(text()) ='Critical Hit Immunity']")
filter_loc_Damage_Immunity = ("xpath", "//a[normalize-space(text()) ='Damage Immunity']")
filter_loc_Daze = ("xpath", "//a[normalize-space(text()) ='Daze']")
filter_loc_Deathmark = ("xpath", "//a[normalize-space(text()) ='Deathmark']")
filter_loc_Defence_Down = ("xpath", "//a[normalize-space(text()) ='Defence Down']")
filter_loc_Defence_Penetration_Up = ("xpath", "//a[normalize-space(text()) ='Defence Penetration Up']")
filter_loc_Defence_Up = ("xpath", "//a[normalize-space(text()) ='Defence Up']")
filter_loc_Dispel = ("xpath", "//a[normalize-space(text()) ='Dispel']")
filter_loc_Dispel_All_Allies = ("xpath", "//a[normalize-space(text()) ='Dispel - All Allies']")
filter_loc_Dispel_All_Enemies = ("xpath", "//a[normalize-space(text()) ='Dispel - All Enemies']")
filter_loc_DoT = ("xpath", "//a[normalize-space(text()) ='DoT']")
filter_loc_Doubt = ("xpath", "//a[normalize-space(text()) ='Doubt']")
filter_loc_Evasion_Down = ("xpath", "//a[normalize-space(text()) ='Evasion Down']")
filter_loc_Evasion_Up = ("xpath", "//a[normalize-space(text()) ='Evasion Up']")
filter_loc_Expose = ("xpath", "//a[normalize-space(text()) ='Expose']")
filter_loc_Fear = ("xpath", "//a[normalize-space(text()) ='Fear']")
filter_loc_Foresight = ("xpath", "//a[normalize-space(text()) ='Foresight']")
filter_loc_Frenzy = ("xpath", "//a[normalize-space(text()) ='Frenzy']")
filter_loc_Gain_Turn_Meter = ("xpath", "//a[normalize-space(text()) ='Gain Turn Meter']")
filter_loc_Heal = ("xpath", "//a[normalize-space(text()) ='Heal']")
filter_loc_Healing_Immunity = ("xpath", "//a[normalize-space(text()) ='Healing Immunity']")
filter_loc_Health_Steal_Up = ("xpath", "//a[normalize-space(text()) ='Health Steal Up']")
filter_loc_Health_Up = ("xpath", "//a[normalize-space(text()) ='Health Up']")
filter_loc_Inspired = ("xpath", "//a[normalize-space(text()) ='Inspired']")
filter_loc_Instant_Defeat_Immunity = ("xpath", "//a[normalize-space(text()) ='Instant Defeat Immunity']")
filter_loc_Leader_Critical_Up = ("xpath", "//a[normalize-space(text()) ='Leader: +Critical']")
filter_loc_Leader_Defense_Up = ("xpath", "//a[normalize-space(text()) ='Leader: +Defense']")
filter_loc_Leader_Evasion_Up = ("xpath", "//a[normalize-space(text()) ='Leader: +Evasion']")
filter_loc_Leader_Max_Health_Up = ("xpath", "//a[normalize-space(text()) ='Leader: +Max Health']")
filter_loc_Leader_Speed_Up = ("xpath", "//a[normalize-space(text()) ='Leader: +Speed']")
filter_loc_Leader_Tenacity_Up = ("xpath", "//a[normalize-space(text()) ='Leader: +Tenacity']")
filter_loc_Leader_Assist = ("xpath", "//a[normalize-space(text()) ='Leader: Assist']")
filter_loc_Leader_Foresight = ("xpath", "//a[normalize-space(text()) ='Leader: Foresight']")
filter_loc_Leader_Healing = ("xpath", "//a[normalize-space(text()) ='Leader: Healing']")
filter_loc_Leader_Health_Up = ("xpath", "//a[normalize-space(text()) ='Leader: Health Up']")
filter_loc_Leader_Protection_Up = ("xpath", "//a[normalize-space(text()) ='Leader: Protection Up']")
filter_loc_Offense_Down = ("xpath", "//a[normalize-space(text()) ='Offense Down']")
filter_loc_Offense_Up = ("xpath", "//a[normalize-space(text()) ='Offense Up']")
filter_loc_Plague = ("xpath", "//a[normalize-space(text()) ='Plague']")
filter_loc_Potency_Down = ("xpath", "//a[normalize-space(text()) ='Potency Down']")
filter_loc_Potency_Up = ("xpath", "//a[normalize-space(text()) ='Potency Up']")
filter_loc_Provoked = ("xpath", "//a[normalize-space(text()) ='Provoked']")
filter_loc_Protection_Up = ("xpath", "//a[normalize-space(text()) ='Protection Up']")
filter_loc_Purge = ("xpath", "//a[normalize-space(text()) ='Purge']")
filter_loc_Reduce_Cooldowns = ("xpath", "//a[normalize-space(text()) ='Reduce Cooldowns']")
filter_loc_Remove_Turn_Meter = ("xpath", "//a[normalize-space(text()) ='Remove Turn Meter']")
filter_loc_Reset_Cooldown = ("xpath", "//a[normalize-space(text()) ='Reset Cooldown']")
filter_loc_Revive = ("xpath", "//a[normalize-space(text()) ='Revive']")
filter_loc_Riposte = ("xpath", "//a[normalize-space(text()) ='Riposte']")
filter_loc_Shock = ("xpath", "//a[normalize-space(text()) ='Shock']")
filter_loc_Speed_Down = ("xpath", "//a[normalize-space(text()) ='Speed Down']")
filter_loc_Speed_Up = ("xpath", "//a[normalize-space(text()) ='Speed Up']")
filter_loc_Stagger = ("xpath", "//a[normalize-space(text()) ='Stagger']")
filter_loc_Stealth = ("xpath", "//a[normalize-space(text()) ='Stealth']")
filter_loc_Stun = ("xpath", "//a[normalize-space(text()) ='Stun']")
filter_loc_Target_Lock = ("xpath", "//a[normalize-space(text()) ='Target Lock']")
filter_loc_Taunt = ("xpath", "//a[normalize-space(text()) ='Taunt']")
filter_loc_Tenacity_Down = ("xpath", "//a[normalize-space(text()) ='Tenacity Down']")
filter_loc_Tenacity_Up = ("xpath", "//a[normalize-space(text()) ='Tenacity Up']")
filter_loc_Thermal_Detonator = ("xpath", "//a[normalize-space(text()) ='Thermal Detonator']")
filter_loc_Torture = ("xpath", "//a[normalize-space(text()) ='Torture']")
filter_loc_Vulnerable = ("xpath", "//a[normalize-space(text()) ='Vulnerable']")
#
#
#
all_characters_loc = ("xpath", "//li[@class = 'media list-group-item p-0 character']")
selected_filter_loc = ('xpath', '//div[@class = "fw-bold"]')
