from selenium.webdriver.common.by import By


filter_button_loc = (By.XPATH, "//button[@class='btn btn-default']")
filter_list_loc = (By.XPATH, "//div[@class='modal-body p-a-0 categories']/div[@class='modal-body-scroller']"
                             "/div[@class='media-list media-list-users list-group']")
ability_button_filter_loc = (By.XPATH, "//a[text()='Ability Classes']")
alignments_button_filter_loc = (By.XPATH, "//a[text()='Alignments']")
filtered_characters_loc = (By.XPATH, "//small[@class='pull-right']")
filter_loc_501 = (By.XPATH, "//strong[text()='501st']")
filter_loc_Attacker = (By.XPATH, "//strong[text()='Attacker']")
filter_loc_Bad_Batch = (By.XPATH, "//strong[text()='Bad Batch']")
filter_loc_Bounty_Hunter = (By.XPATH, "//strong[text()='Bounty Hunter']")
filter_loc_Clone_Trooper = (By.XPATH, "//strong[text()='Clone Trooper']")
filter_loc_Droid = (By.XPATH, "//strong[text()='Droid']")
filter_loc_Empire = (By.XPATH, "//strong[text()='Empire']")
filter_loc_Ewok = (By.XPATH, "//strong[text()='Ewok']")
filter_loc_First_Order = (By.XPATH, "//strong[text()='First Order']")
filter_loc_Fleet_Commander = (By.XPATH, "//strong[text()='Fleet Commander']")
filter_loc_Galactic_Legend = (By.XPATH, "//strong[text()='Galactic Legend']")
filter_loc_Galactic_Republic = (By.XPATH, "//strong[text()='Galactic Republic']")
filter_loc_Geonosian = (By.XPATH, "//strong[text()='Geonosian']")
filter_loc_Healer = (By.XPATH, "//strong[text()='Healer']")
filter_loc_Hutt_Cartel = (By.XPATH, "//strong[text()='Hutt Cartel']")
filter_loc_Imperial_Remnant = (By.XPATH, "//strong[text()='Imperial Remnant']")
filter_loc_Imperial_Trooper = (By.XPATH, "//strong[text()='Imperial Trooper']")
filter_loc_Inquisitorius = (By.XPATH, "//strong[text()='Inquisitorius']")
filter_loc_Jawa = (By.XPATH, "//strong[text()='Jawa']")
filter_loc_Jedi = (By.XPATH, "//strong[text()='Jedi']")
filter_loc_Leader = (By.XPATH, "//strong[text()='Leader']")
filter_loc_Mandalorian = (By.XPATH, "//strong[text()='Mandalorian']")
filter_loc_Nightsister = (By.XPATH, "//strong[text()='Nightsister']")
filter_loc_Old_Republic = (By.XPATH, "//strong[text()='Old Republic']")
filter_loc_Phoenix = (By.XPATH, "//strong[text()='Phoenix']")
filter_loc_Rebel = (By.XPATH, "//strong[text()='Rebel']")
filter_loc_Rebel_Fighter = (By.XPATH, "//strong[text()='Rebel Fighter']")
filter_loc_Resistance = (By.XPATH, "//strong[text()='Resistance']")
filter_loc_Rogue_One = (By.XPATH, "//strong[text()='Rogue One']")
filter_loc_Scoundrel = (By.XPATH, "//strong[text()='Scoundrel']")
filter_loc_Separatist = (By.XPATH, "//strong[text()='Separatist']")
filter_loc_Sith = (By.XPATH, "//strong[text()='Sith']")
filter_loc_Sith_Empire = (By.XPATH, "//strong[text()='Sith Empire']")
filter_loc_Smuggler = (By.XPATH, "//strong[text()='Smuggler']")
filter_loc_Support = (By.XPATH, "//strong[text()='Support']")
filter_loc_Tank = (By.XPATH, "//strong[text()='Tank']")
filter_loc_Tusken = (By.XPATH, "//strong[text()='Tusken']")
filter_loc_Unaligned_Force_User = (By.XPATH, "//strong[text()='Unaligned Force User']")
filter_loc_Wookiee = (By.XPATH, "//strong[text()='Wookiee']")
filter_loc_Light_Side = (By.XPATH, "//strong[text()='Light Side']")
filter_loc_Dark_Side = (By.XPATH, "//strong[text()='Dark Side']")
filter_loc_Neutral = (By.XPATH, "//strong[text()='Neutral']")
